package Juego;

import java.awt.Window;

import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

import Juego.CreateStage;

public class GameController extends javax.swing.JFrame {

    int playerID = 0;
    int arr[][];
    public player localPlayer = null;
    String[] posIniciales = { "30 13"};
    int xInit = 39, yInit = 6;
    Stage escenario = null;
    CreateStage mEsc;
    private int posBomX = -1;
    private int posBomY = -1;
    
    public GameController() {
        initComponents();
    }

    public player getCharacter() {
        return this.localPlayer;
    }
    
    public Stage getEscenario() {
    	return this.escenario;
    }

    public void setPlayerID(int id) {
        System.out.println("Se esta iniciando el juego...");
        this.playerID = id;
        String[] pos = posIniciales[(id - 1)%5].split("\\s");
        this.xInit = Integer.parseInt(pos[0]);
        this.yInit = Integer.parseInt(pos[1]);
        startGame();
    }

    public void setPlayerAtPosition(int id, int x, int y) {
        // 1 --> '1'
        // this.escenario.mostrarEscenario();
        if (!this.posIniciales[(id - 1)%5].equals((x) + " " + (y))) {
            this.escenario.setCaracterEnCoordenada((char) (id + 48), x, y);
            String[] posDeJugador = this.posIniciales[(id - 1)%5].split("\\s");
            int xPast = Integer.parseInt(posDeJugador[0]);
            int yPast = Integer.parseInt(posDeJugador[1]);
            this.escenario.limpiarCoordenaDelEscenario(xPast, yPast);
            this.escenario.mostrarEscenario();
            this.posIniciales[(id - 1)%5] = x + " " + y;
            //System.out.println("x past + y past" + xPast + " " + yPast + " " + this.posIniciales[id - 1]);
        }
    }
    
    public void setBombaAtPosition(int x, int y) {
    	//System.out.println(x + y);
        this.escenario.setCaracterEnCoordenada('@', x, y);

        this.escenario.mostrarEscenario();
        (new Bullet(x,y,this.escenario, this.localPlayer)).start();
    }
    
    public int getPosBomX() {
		return posBomX;
	}

	public void setPosBomX(int posBomX) {
		this.posBomX = posBomX;
	}

	public int getPosBomY() {
		return posBomY;
	}

	public void setPosBomY(int posBomY) {
		this.posBomY = posBomY;
	}

	public void startGame() {
        mEsc = new CreateStage(xInit, yInit);
        this.localPlayer = mEsc.getJugador();
        mEsc.iniciar();
        this.escenario = mEsc.getEscenario();
        this.setVisible(true);
        this.setTitle("Mando jugador " + (this.playerID));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Izquierda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Arriba");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Derecha");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Abajo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Disparar");
        jButton5.setActionCommand("Bullet");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(65, 65, 65))))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButton4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton2)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        isAlive();
    	localPlayer.dropBomb(localPlayer.getx(), localPlayer.gety(), localPlayer.getMapa());
        setPosBomX(localPlayer.getx());
        setPosBomY(localPlayer.gety());
        localPlayer.setHasBomb(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
    	isAlive();
        localPlayer.man_left();
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
    	isAlive();
    	localPlayer.man_up();
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
    	isAlive();
    	localPlayer.man_right();
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
    	isAlive();
    	localPlayer.man_down();
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton4ActionPerformed

    public void isAlive() {
    	if (!escenario.isUserAlive()) {
    		localPlayer.kill_character();
    		System.exit(0);
    	}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
